sudo: required
language: node_js
node_js:
  - "13"
services:
  - docker

install:
  - npm install

env:
  - DOCKER_COMPOSE_VERSION=1.16.1

script:
  - echo "npm test"

deploy:
  provider: heroku
  api_key: $API_KEY
  app: tfm-front-repositorio
  on:
    branch: master
after_success:
  - sudo docker login --username $HEROKU_DOCKER_USERNAME --password $API_KEY registry.heroku.com
  - sudo docker tag tfm-front:latest registry.heroku.com/tfm-front-repositorio/web
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then sudo docker push registry.heroku.com/tfm-front-repositorio/web; fi