version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tfm-front
    image: tfm-front
    networks:
      - prod-network
    ports:
      - '80:80'
    environment:
    - PORT=80
 
networks:
  prod-network:
    driver: bridge